[package]
name = "nmap-ebpf"
version.workspace = true
edition.workspace = true
description = "nmap eBPF implementation for Kali Plasma"

[dependencies]
plasma-ebpf-common = { path = "../common" }

[lib]
crate-type = ["cdylib"]

[features]
default = []




