apiVersion: v1
kind: Secret
metadata:
  name: ctas-secrets
type: Opaque
data:
  mongodb-root-password: Y2hhbmdlbWU= # changeme
  neo4j-password: Y2hhbmdlbWU= # changeme
  postgres-password: Y2hhbmdlbWU= # changeme
  opencti-admin-password: YWRtaW4= # admin
  opencti-admin-token: Y2hhbmdlbWU= # changeme