version: "3.9"
services:
  neo4j:
    image: neo4j:5
    container_name: sx9_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/testpassword
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_auth__minimum__password__length: 8
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/import
      - ../neo4j:/schema:ro
